# Generated by Django 4.2.2 on 2023-06-13 09:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("graph", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Champs",
            fields=[
                ("name", models.CharField(max_length=50)),
                ("id", models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "champs",
                "managed": False,
            },
        ),
    ]
