# Generated by Django 4.2.2 on 2023-06-13 09:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("graph", "0002_champs"),
    ]

    operations = [
        migrations.CreateModel(
            name="Items",
            fields=[
                ("name", models.CharField(max_length=100)),
                ("id", models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "items",
                "managed": False,
            },
        ),
    ]
