# Generated by Django 4.2.2 on 2023-06-13 14:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("graph", "0003_items"),
    ]

    operations = [
        migrations.CreateModel(
            name="SummonerSpells",
            fields=[
                ("name", models.CharField(max_length=100)),
                ("id", models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "summoner_spells",
                "managed": False,
            },
        ),
    ]
