# Generated by Django 4.2.2 on 2023-06-20 09:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("graph", "0006_champstats_champ_kda_champstats_champ_lvl_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="champstats",
            name="champ_dmgtype",
            field=models.CharField(blank=True, default="", max_length=50, null=True),
        ),
    ]
