# Generated by Django 4.2.2 on 2023-06-23 12:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("graph", "0009_alter_champstats_champ_item_set"),
    ]

    operations = [
        migrations.RenameField(
            model_name="champstats",
            old_name="champ_item_set",
            new_name="champ_item_set_five_item",
        ),
        migrations.AddField(
            model_name="champstats",
            name="champ_item_set_four_item",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name="champstats",
            name="champ_item_set_one_item",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name="champstats",
            name="champ_item_set_six_item",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name="champstats",
            name="champ_item_set_three_item",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name="champstats",
            name="champ_item_set_two_item",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
